name: Deploy via Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  basion-buld-deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Copy build to Private VM
      run: |
        echo "Copying the dist to the basion server..."
        scp -r ./dist azureuser@20.63.24.50:/home/azureuser/
        echo "ssh to basion server..."
        ssh azureuser@20.63.24.50 
        echo "Remove the dist from vm.."
        ssh azureuser@10.0.0.4 'rm -rf /home/azureuser/git_app_1/dist'
        echo "Back to the basion server..."
        exit
        echo "Copying the dist to the vm from basion server..."
        scp -r ./dist azureuser@10.0.0.4:/home/azureuser/git_app_1/
        echo "Removing  the dist from basion server..."
        sudo -rm -r ./dist

    - name: Restart Nginx on Private VM
      run: |
        echo "Restarting Nginx on Private VM...."
        ssh azureuser@10.0.0.4 'sudo systemctl restart nginx'
