name: Deploy via Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  basion-buld-deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Copy build through Bastion
      run: |
        echo "📦 Step 1: Copy dist to Bastion server..."
        scp -r ./dist azureuser@20.63.24.50:/home/azureuser/
        echo "🧹 Step 2: Remove old dist from Private VM..."
        ssh azureuser@20.63.24.50 'ssh azureuser@10.0.0.4 "rm -rf /home/azureuser/git_app_1/dist"'
        echo "📤 Step 3: Copy new dist from Bastion to Private VM..."
        ssh azureuser@20.63.24.50 'scp -r /home/azureuser/dist azureuser@10.0.0.4:/home/azureuser/git_app_1/'
        echo "🧼 Step 4: Remove dist from Bastion server..."
        ssh azureuser@20.63.24.50 'rm -rf /home/azureuser/dist'
  

    - name: Restart Nginx on Private VM
      run: |
        echo "Restarting Nginx on Private VM....."
        ssh azureuser@20.63.24.50 'ssh azureuser@10.0.0.4 "sudo systemctl restart nginx"'
